### PR TITLE
Multi thermistor support2

### PR DESCRIPTION
**Pull request by imarin2**
Previous branch hotend_3DA-002_beta_3950_260C_thermistor rebased and squashed with minor conditional compilation fixes.

I have been using this for a week without any issue.

New feature: Multi-thermistor hotswap support

Status: Compiles and tested

Description:
- It allows to change the thermistor type via gcode
- It allows setting the maximum temperature of the hotend via gcode
- The hotswap is interrupt save (stops interrupts during change)
- Feature can be fully removed from firmware (conditional compilation)

See commit comments for more information and forum thread:
http://forum.fabtotum.cc/showthread.php?2474-Extruder-thermistor-support

### CODE REVIEW

**Comment by imarin2** [comment]
@FABtotum 
Can I have some update on the status of this pull request? Are you planning to integrate it?

**Comment by marco-fabteam** [comment]
Hi Imarin, Thanks for your contribution.
The pull request is up-to-date so it might be merged as soon as tested.
It will most probably be merged to be featured in the next release.

cheers!

**Comment by imarin2** [comment]
Would you also merge this if I do a pull request?
https://github.com/imarin2/FABlin/commits/skintoss_endstop_fix

**Comment by marco-fabteam** [comment]
Sure, why not?
We are focusing on software versioning for v2 heads and v2 plates right now, so the next firmware update is still a month away.

**Comment by imarin2** [comment]
Ok. Because the work on the extended endstop inverting was done in my branch on top of the multi-thermistor support, it is preferable to close this pull request and directly merge the one in #9, which includes both.

**Pull request closed without merging**
